version: '3'

services:
  api-gateway:
    build: 
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    depends_on:
      - mongodb
      - redis

  booking-service:
    build: 
      context: ./booking-service
      dockerfile: Dockerfile
    ports:
      - "8003:8003"
    depends_on:
      - mongodb
      - redis

  hotel-service:
    build: 
      context: ./hotel-service
      dockerfile: Dockerfile
    ports:
      - "8001:8001"
    depends_on:
      - mongodb
      - redis

  notif-service:
    build: 
      context: ./notif-service
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis

  user-service:
    build: 
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data

volumes:
  mongodb_data:
  redis_data: