server:
  host: api-gateway
  port: 9000

hotel_service:
  host: hotel-service
  port: 8001

user_service:
  host: user-service
  port: 8002

booking_service:
  host: booking-service
  port: 8003

notification_service:
  host: notif-service
  port: 3000

redis:
  host: redis
  port: 6379

secretKey: bekzodbekk_mongosh

tls:
  cert: "./localhost.pem"
  key: "./localhost-key.pem"
